#!/bin/sh
PYVER=$(ls "$SNAP/lib/" | grep -E '^python3\.[0-9]+$' | sort -V | tail -1)
export PYTHONPATH="$SNAP/lib/$PYVER/site-packages"
export TCL_LIBRARY="$SNAP/usr/share/tcltk/tcl8.6"
export TK_LIBRARY="$SNAP/usr/share/tcltk/tk8.6"
exec "$SNAP/bin/poetit" "$@"
