#!/bin/sh
# Regenerates python3-requirements.json for offline Flatpak builds.
# Run whenever requirements.txt changes or the runtime (its python) is bumped.
#
# Method: resolve the full dependency set as BINARY wheels using pip's
# install report, executed inside the GNOME SDK sandbox so the resolution
# matches the runtime python exactly (cp313 for GNOME 50). Source builds are
# a dead end here: the scientific stack (numpy/scipy/pandas) needs
# meson-python and gfortran, which the SDK does not ship.
#
# torch handling: pip resolves PyPI's CUDA torch (plus its nvidia-* payload)
# for stanza's torch>=1.13; the transform below drops torch, the nvidia-*
# packages, and everything python3-torch-cpu.json already installs. That
# module must stay listed BEFORE this one in the manifest.
#
# Note: the platform wheels pin x86_64 URLs. An aarch64 Flathub build needs a
# second resolution pass on that architecture (or only-arches splitting).
set -e
cd "$(dirname "$0")"

RUNTIME=${RUNTIME:-org.gnome.Sdk//50}
flatpak run --share=network --filesystem=home --command=sh "$RUNTIME" -c \
    "python3 -m pip install -q --dry-run --ignore-installed --prefer-binary \
        --report '$PWD/pip-report.json' -r '$PWD/requirements.txt'"

python3 - <<'EOF'
import json

report = json.load(open('pip-report.json'))
torch_owned = {'torch', 'sympy', 'mpmath', 'networkx', 'jinja2', 'markupsafe',
               'filelock', 'fsspec', 'typing-extensions', 'typing_extensions'}
sources, names = [], []
for item in report['install']:
    name = item['metadata']['name']
    norm = name.lower().replace('_', '-')
    if (norm in torch_owned or norm.startswith('nvidia-')
            or norm.startswith('cuda-') or norm == 'triton'):
        continue
    dl = item['download_info']
    sha = dl.get('archive_info', {}).get('hashes', {}).get('sha256')
    if not sha:
        raise SystemExit(f"no sha256 for {name}")
    entry = {"type": "file", "url": dl['url'], "sha256": sha}
    if not dl['url'].endswith('.whl') or 'none-any' not in dl['url']:
        entry["comment"] = "platform-specific"
    sources.append(entry)
    names.append(name)

module = {
    "name": "python3-requirements",
    "comment": ("Generated by flatpak/generate-pip-sources.sh: the full "
                "dependency set resolved as binary wheels for the runtime "
                "python (cp313, GNOME 50) via pip's --report inside the SDK "
                "sandbox. torch and the packages the python3-torch-cpu.json "
                "module installs are excluded."),
    "buildsystem": "simple",
    "build-commands": [
        "pip3 install --verbose --exists-action=i --no-index --find-links=\"file://${PWD}\" "
        "--prefix=${FLATPAK_DEST} --no-build-isolation --no-deps " + " ".join(sorted(names))
    ],
    "sources": sources,
}
json.dump(module, open('python3-requirements.json', 'w'), indent=2)
print(f"wrote python3-requirements.json with {len(sources)} wheels")
EOF
rm -f pip-report.json
